import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";
import { SearchQueryProvider } from "@/context/SearchQueryContext"; // Import context

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SearchQueryProvider>
          <SidebarProvider>
            <AppSidebar />
            <main className="p-8">
              <header className="flex h-16 shrink-0 items-center gap-2 border-b">
                <SidebarTrigger className="-ml-1 cursor-pointer" />
              </header>
              {children}
            </main>
          </SidebarProvider>
        </SearchQueryProvider>
      </body>
    </html>
  );
}
